name: <App> Workflow User

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  
  #Build and Run tests
  test:
      uses: submittable/github-actions/.github/workflows/nodejs-ut-ci.yml@main
      secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  #Dockerize app      
  docker-frontend:
      needs: test
      uses: submittable/github-actions/.github/workflows/reusable-docker.yml@main
      with:
      #this is a variable configured within the called workflow. in this case the image_name will be the repo name
        image_name: ${{ github.repository }}
        #context: CHANGEME
      secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #docker-backend:
      #uses: submittable/github-actions/.github/workflows/reusable-docker.yml@main
      #with:
      ##this is a variable configured within the called workflow. in this case the image_name will be the repo name
        #image_name: ${{ github.repository }}
        #context: CHANGEME
      #secrets:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
